# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import add_pb2 as add__pb2


class AddStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAddResult = channel.unary_unary(
                '/addrpc.Add/GetAddResult',
                request_serializer=add__pb2.Numbers.SerializeToString,
                response_deserializer=add__pb2.AddResult.FromString,
                )


class AddServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAddResult(self, request, context):
        """A simple RPC.

        Obtains the MessageResponse at a given position.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AddServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAddResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAddResult,
                    request_deserializer=add__pb2.Numbers.FromString,
                    response_serializer=add__pb2.AddResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'addrpc.Add', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Add(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAddResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/addrpc.Add/GetAddResult',
            add__pb2.Numbers.SerializeToString,
            add__pb2.AddResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
